spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Library
  datasource:
    url: jdbc:h2:./db/Library;AUTO_SERVER=TRUE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

  mvc:
    static-path-pattern: /static/**
    log-request-details: true
  freemarker:
    expose-session-attributes: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
    show-sql: false

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

logging:
  level:
    root: info
    org:
      springframework:
        security: error
      hibernate:
        stat: error
        type: error
    sql: error
    web: error
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  file:
    path: logs
